In [1]:

#!python3 -m pip install kaggle
#!python3 -m pip install openpyxl

import pandas as pd
import zipfile
import kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (1.6.14)
Requirement already satisfied: six>=1.10 in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/site-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi>=2023.7.22 in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from kaggle) (2024.6.2)
Requirement already satisfied: python-dateutil in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from kaggle) (2.32.3)
Requirement already satisfied: tqdm in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from kaggle) (4.66.4)
Requirement already satisfied: python-slugify in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from kaggle) (2.2.2)
Requirement already satisfied: bleach in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/patricioguerra/Library/Python/3.9/lib/python/site-packages (from requests->kaggle) (3.7)
Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl.metadata (1.8 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.9/250.9 kB 2.0 MB/s eta 0:00:00 0:00:01
Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.5
Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/patricioguerra/.kaggle/kaggle.json'

/Users/patricioguerra/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(

In [2]:

!kaggle datasets download -d hmavrodiev/london-bike-sharing-dataset

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /Users/patricioguerra/.kaggle/kaggle.json'
Dataset URL: https://www.kaggle.com/datasets/hmavrodiev/london-bike-sharing-dataset
License(s): other
london-bike-sharing-dataset.zip: Skipping, found more recently modified local copy (use --force to force download)

In [3]:
zipfile_name = 'london-bike-sharing-dataset.zip'

with zipfile.ZipFile(zipfile_name,'r') as file:
    file.extractall()

In [3]:
bikes = pd.read_csv('london_merged.csv')
bikes.head()

,timestamp,cnt,t1,t2,hum,wind_speed,weather_code,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [5]:
new_col_names = {
    'timestamp':'time',
    'cnt':'count',
    't1':'temp_real_C',
    't2':'temp_feels_like_C',
    'hum':'humidity_percent',
    'wind_speed':'wind_speed_kph',
    'weather_code':'weather',
    'is_holiday':'is_holiday',
    'is_weekend':'is_weekend',
    'season':'season'
}

bikes.rename(new_col_names,axis=1,inplace=True)

bikes.head()

,time,count,temp_real_C,temp_feels_like_C,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,93.0,6.0,3.0,0.0,1.0,3.0
1,2015-01-04 01:00:00,138,3.0,2.5,93.0,5.0,1.0,0.0,1.0,3.0
2,2015-01-04 02:00:00,134,2.5,2.5,96.5,0.0,1.0,0.0,1.0,3.0
3,2015-01-04 03:00:00,72,2.0,2.0,100.0,0.0,1.0,0.0,1.0,3.0
4,2015-01-04 04:00:00,47,2.0,0.0,93.0,6.5,1.0,0.0,1.0,3.0

In [6]:
bikes.humidity_percent = bikes.humidity_percent / 100


season_dict = {
    '0.0':'spring',
    '1.0':'summer',
    '2.0':'autumn',
    '3.0':'winter'
}


weather_dict = {
    '1.0':'Clear',
    '2.0':'Scattered clouds',
    '3.0':'Broken clouds',
    '4.0':'Cloudy',
    '7.0':'Rain',
    '10.0':'Rain with thunderstorm',
    '26.0':'Snowfall'
}


bikes.season = bikes.season.astype('str')

bikes.season = bikes.season.map(season_dict)


bikes.weather = bikes.weather.astype('str')

bikes.weather = bikes.weather.map(weather_dict)

bikes.head()

,time,count,temp_real_C,temp_feels_like_C,humidity_percent,wind_speed_kph,weather,is_holiday,is_weekend,season
0,2015-01-04 00:00:00,182,3.0,2.0,0.930,6.0,Broken clouds,0.0,1.0,winter
1,2015-01-04 01:00:00,138,3.0,2.5,0.930,5.0,Clear,0.0,1.0,winter
2,2015-01-04 02:00:00,134,2.5,2.5,0.965,0.0,Clear,0.0,1.0,winter
3,2015-01-04 03:00:00,72,2.0,2.0,1.000,0.0,Clear,0.0,1.0,winter
4,2015-01-04 04:00:00,47,2.0,0.0,0.930,6.5,Clear,0.0,1.0,winter

In [7]:
bikes.to_excel('london_bikes_final.xlsx', sheet_name='Data')